Resources: 
  LoadBalancer:
    Type: AWS::EC2::Instance
    Properties:
  
  Secrets:
    Type: AWS::SSM::Parameter
    Properties:
    
  Application:
    Type: AWS::ECS::TaskDefinition
    Properties:
      
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 locked down to the load balancer + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp: !Ref SSHLocation
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
