version: 2
jobs:
  build:
    docker:
      - image: csr2131/libreoffice-base
    steps:
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: | 
            python3 -m venv venv 
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Run Tests
          command: echo "TODO: implements tests"
      #- run: #deploy app to ec2
