version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install CI dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache: 
          keys: 
            - v1-{{ .Branch }}
          paths: 
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=csr2131/slidegraph -t csr2131/slidegraph .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar csr2131/slidegraph
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run Tests
          command: echo "TODO implements tests"
      - run:
          name: Push New Image to Docker Hub
          command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              echo "updating image"
              docker push csr2131/slidegraph
            fi

      
